### ISSUE TITLE
Firmware download according to README.md results in unusable file which bricks device when flashed back

### ISSUE THREAD

**Issue by smiley** [Massdrop/mdloader#1]
I wanted to test something out and needed to remap a key, so I made a layout on the configurator and flashed it. Before I did, however, I made sure to read my CTRL's stock firmware into a file with: (`mdloader --list` reported my keyboard at `COM3`)
```cmd
mdloader --port COM3 --upload read_firmware.bin --addr 0x4000 --size 0x10000
```
When I was done with testing, I flashed the same file back and the keyboard failed to boot. I tried going back into bootloader mode and flashing again several more times, unplugging + replugging it after the flash was done, but it stayed off. Luckily flashing a standard preset off the configurator was enough to bring it back.

[Here's](https://github.com/Massdrop/mdloader/files/2386040/massdrop_ctrl_stock.zip) the stock firmware resulting from the command line above, if necessary.

**Comment by Fuhrmann** [comment]
Did you solved this problem? Is the resulting file really corrupted? I am about to change my firmware and wanted to download a backup before proceeding.
