### ISSUE TITLE
--list never finds device on Arch Linux without using sudo

### ISSUE THREAD

**Issue by doughsay** [Massdrop/mdloader#11]
The `dialout` group doesn't exist on Arch Linux; adding the group and adding my user to that group does't have any effect.

What can I do to use this without having to use root/sudo?

**Comment by jimbojim** [comment]
I'm having the same problem. Any update yet?

**Comment by buldozer911** [comment]
Same issue here with my alt. Could not find a valid device port! even with sudo
OS: Manjaro-i3
Massdrop Loader version 1.03

**Comment by wazlecracker** [comment]
Encountering the same issue. On Manjaro and had to use sudo to get the software to detect the keyboard.

**Comment by tieum** [comment]
Encountered the same issue on Manjaro. For Arch Linux, you need to add yourself to the `uucp` group.

**Comment by su45** [comment]
Same issue on Fedora.
```
[suddin@hydrogen ~]$ sudo mdloader_linux -l
Massdrop Loader 1.03

Massdrop Loader  Copyright (C) 2018  Massdrop Inc.
This program is Free Software and has ABSOLUTELY NO WARRANTY

Bootloader port listing
-----------------------------
No devices found!
```
OS: Fedora 30
mdloader version 1.0.3

Added myself to `dialout`, tried running with `sudo`. Nothing works. Can see the device with `lsusb`:
```
[suddin@hydrogen ~]$ lsusb | grep Massdrop
Bus 003 Device 011: ID 04d8:eec5 Microchip Technology, Inc. Massdrop Hub
```

**Comment by joestump** [comment]
I'm seeing the same issue on macOS as well. Mojave 10.14.6. I'm typing this on my Drop ALT while getting this error:

```
joestump-ltm1:bin joe.stump$ ./mdloader_mac -f -D /Users/joe.stump/Downloads/massdrop_alt_md_configurator_1588978206_665999412.bin --restart
Massdrop Loader 1.03

Massdrop Loader  Copyright (C) 2018  Massdrop Inc.
This program is Free Software and has ABSOLUTELY NO WARRANTY

Scanning for device for 60 seconds
............................................................
Error: Could not find a valid device port!
```

**Comment by daverogers** [comment]
Seeing this on MacOS as well. Even running as root, getting "No devices found!" upon --list. Spending nearly $400 and not being able to map the command key is less than ideal.

**Comment by manuelxaguilar** [comment]
> Scanning for device for 60 seconds
> ............................................................
> Error: Could not find a valid device port!

Same here on Catalina.

**Comment by manuelxaguilar** [comment]
> Seeing this on MacOS as well. Even running as root, getting "No devices found!" upon --list. Spending nearly $400 and not being able to map the command key is less than ideal.

For others having issues on Mac, I just got it to work, I honestly just started pressing Fn+B before the 60 seconds were over and it worked. Just give that a try.
