### ISSUE TITLE
mdloader can't find applet-flash-samd51j18a.bin unless in working directory

### ISSUE THREAD

**Issue by tzarc** [Massdrop/mdloader#21]
At least in the case of Windows, `mdloader` is incapable of programming a CTRL unless `applet-flash-samd51j18a.bin` is in the current working directory.

We've been attempting to allow for QMK to use the `:flash` target to invoke mdloader, but given that it's executed from the `qmk_firmware` directory, `applet-flash-samd51j18a.bin` doesn't exist.

However, if executing `mdloader` from a directory that contains `applet-flash-samd51j18a.bin`, this works. Having `applet-flash-samd51j18a.bin` present next to `mdloader` does not result in a successful flash.

Perhaps searching the executable directory for a copy of `applet-flash-samd51j18a.bin` might be in order?

**Comment by fauxpark** [comment]
Looking at how avrdude handles finding its conf file - it seems that on Windows, it uses [`SearchPath()`](http://svn.savannah.gnu.org/viewvc/avrdude/trunk/avrdude/confwin.c?revision=1311&view=markup) and thus avrdude.conf must be in the `%PATH%` or the CWD. On Linux, the location is derived from `sysconfdir` provided by make: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

mdloader could possibly do a similar thing to resolve the applet, but use `datadir` for `/usr/local/share` on Linux. This would greatly help with packaging for Homebrew, MSYS2 and the various Linux distros.
