### ISSUE TITLE
Linux Mint 19.3 - mdloader_linux: command not found

### ISSUE THREAD

**Issue by hwamil** [Massdrop/mdloader#23]
I threw all necessary files (applet.bin, mdloader_linux, and custom fw) into the same directory and used "chmod u+x mdloader_linux" to make it executable, but when I run mdloader_linux in terminal all I get is the output "command not found". It doesn't matter which arguments or flags go in, it just doesn't find mdloader_linux at all. Working directory is definitely the mdloader directory, so I'm not sure what's up. I've tried sudo/root, and that doesn't work either. I downloaded the source so I could 'make' it, but that also failed.

fyi - I'm on a late 2011 mbp with no dual-boot.

**Comment by AFRUITPIE** [comment]
You'll probably want to do `./mdloader_linux ...`, it's mentioned in PR #17 for macOS but the same probably applies in your case.

**Comment by hwamil** [comment]
Just tried it and same thing happened - "./mdloader_linux: command not found"

**Comment by brooke-heaton** [comment]
I'm on linux and I had to use ./mdloader_linux after making it executable.
