### ISSUE TITLE
macOS Error: Could not find a valid device port!

### ISSUE THREAD

**Issue by carlosbelardi** [Massdrop/mdloader#33]
Hey all,

I've been reading through the issues threads here as I try to set up my new Drop Alt low profile keyboard, and have read about some of the issues with newer releases having a different Chip ID than what mdloader is expecting. My keyboard is from the newest batch (shipped out August 18th) and I suspect I may be having a similar issue. 

I've followed all the instructions I've seen listed throughout this repo and made sure I was downloading the most recent version of everything, but no luck. From what I understand the newest mdloader I downloaded from [here](https://github.com/Massdrop/mdloader/releases/tag/1.0.4) was updated in July to deal with new chip IDs but could have that ID changed again?

Any help would be appreciated!

**Comment by carlosbelardi** [comment]
To provide some more context, I ran the code with the --verbose option and this is what I see:

`Scanning for device for 60 seconds
...........Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!
.Opening port '/dev/cu.usbmodem141201'... Success!
Configuring port... 
  Get config... Success!
  Set config... Success!
Setting normal mode... Success!
Write: [w41002018,#]
Closing port... Success!

Error: Could not find a valid device port!`

**Comment by jjpiv** [comment]
Having the same issue with a new ALT barebones keyboard.

**Comment by carlosbelardi** [comment]
> Having the same issue with a new ALT barebones keyboard.

Check out the thread in issue #36! I found my solution there with the new ALT barebones I got in August

**Comment by jjpiv** [comment]
Thanks @carlosbelardi!!
