### ISSUE TITLE
windows Error: Could not open applet file: applet-flash-samd51j18a.bin

### ISSUE THREAD

**Issue by domoaligato** [Massdrop/mdloader#4]
mdloader_windows.exe -p COM4 -D FN_right_app_menu_massdrop_ctrl_md_configurator_1538788531_581988437.bin
Massdrop Loader 1.0

Massdrop Loader  Copyright (C) 2018  Massdrop Inc.
This program is Free Software and has ABSOLUTELY NO WARRANTY

Opening port 'COM4'... Success!
Found MCU: SAMD51J18A
Error: Could not open applet file: applet-flash-samd51j18a.bin
Closing port... Success!

**Comment by BMPGit** [comment]
same error. could not open applet.

**Comment by ConnieCG** [comment]
I am experiencing the same issue as @BMPGit and @domoaligato using both versions "0.0.3" and "1.0.3" of the software. This has bricked my keyboard, as I can not load new firmware onto it after resetting it during the firmware updating process. Attached is a screenshot of the inputs into the Command Prompt (see lower right). 
![ctrl keyboard firmware update software issue](https://user-images.githubusercontent.com/44261132/47150733-8bb2fc80-d2a5-11e8-9fcc-c028604bf469.jpg)

**Comment by h4ppyhacker** [comment]
Download the applet from their releases page and put it in the same folder as your executable and bin file.

**Comment by ConnieCG** [comment]
I already did that. For both versions of the software. It's shown on the image of my desktop, along with what input I put into the cmd prompt. 

@domoaligato @BMPGit 
If you're still having this issue, look at this image. I got it to work by putting the application in the base directory of the drive, "C:\" in my case. 

![ctrl keyboard firmware update_sucess](https://user-images.githubusercontent.com/44261132/47462047-4d8b7080-d7b0-11e8-9637-1687bfa4858d.jpg)

**Comment by domoaligato** [comment]
I did not see the bin file was available to download until now. I am glad that the instructions have been updated. From a user perspective I suggest you zip the exe and bin together and start testing your releases yourself before releasing. Also connieng your device is not bricked. Bricked would mean that you can not longer communicate to the fitness chip at all. Your screenshot shows it identifying the chip. Please be careful throwing around the term bricked.

**Comment by domoaligato** [comment]
-f or --First does not work. I had to use -p COM5 after -l to list the ports
then...
Opening port 'COM5'... Success!
Found MCU: SAMD51J18A
Error: Applet run error!
Closing port... Success!

**Comment by domoaligato** [comment]
btw it did not close the port on it's own. that is from me unplugging it.

**Comment by domoaligato** [comment]
I got it working. derp pebkac
