### ISSUE TITLE
Prevent cli to use wrong bin file (applet-mdflash.bin) instead of firmware.

### ISSUE THREAD

**Issue by debrutal** [Massdrop/mdloader#45]
**Describe the problem**

Hi since i somehow misread the instruction on how to flash the firmware, i accidently used  _applet-mdflash.bin_ to flash my keyboard which broke it. 
The instructions uses 2 bin files, the firmware and applet-mdflash.bin

**mdloader_linux --first --download applet-mdflash.bin --restart**

**Proposed solutions**
a: Have an internal blocklist to not use this specific filename
b: Check that firmware file does not have the same hash of the applet-mdflash.bin file

**Comment by mbladel** [comment]
Hello @debrutal,
did you manage to get the keyboard working again after?

I tried re-flashing it with the right file but the keyboard is not recognized, none of the leds are turning on.
Let me know if you can, thanks.

**Comment by debrutal** [comment]
i could manage to flash the keyboard. 
flashing the first time it was working without sudo. 
Flashing it again needed sudo rigths

**Comment by debrutal** [comment]
@mbladel If you situation is still an issue, please open an issue with a brief description of your case.

I am closing this for now, since my flashing worked fine
