### ISSUE TITLE
Drop SHIFT keyboard

### ISSUE THREAD

**Issue by cheeserole** [Massdrop/mdloader#52]
mdloader has trouble loading the SHIFT. I would appreciate a release explicitly supporting it.

**Comment by CronianIce** [comment]
Same issue here, mloader can't find the device and so it never uploads the firmware.

**Comment by CronianIce** [comment]
You have the put the keyboard into DFU mode with Fn+B (hold for 3 seconds) first. Make sure you have another backup keyboard around so that you can enter the command. Also, you have to have applet-mdflash.bin downloaded in the same directory. Hopefully this helps you.
