### ISSUE TITLE
Request for the Corresponding Source for applet-flash-samd51j18a.bin

### ISSUE THREAD

**Issue by zedinosaur** [Massdrop/mdloader#6]
Under the terms of the GPLv3 I would like to request the source code used to generate the applet-flash-samd51j18a.bin object file.

**Comment by wildcat2083** [comment]
Im also Interested in where to build the source for the chip ( applet-flash-samd51j18a.bin), from my understanding its specifically for the ATSAMD51j18a Chip, I found some resources but its vague as to exactly how to use the tools in the thread
https://github.com/qmk/qmk_firmware/issues/4194

http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-ICE_UserGuide.pdf   >> Atmel-ICE User Guide
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0316d/Chdiaihc.html  >> ARM SWD Information
https://www.microchip.com/mplab/avr-support/atmel-studio-7  >> Atmel Studio

The applet comes prebuilt in the mdloader files for massdrop(s) ctrl and alt keyboards

**Comment by TheZoc** [comment]
I'd like to bump this and ask for the source code for the applet as well.

**Comment by TheZoc** [comment]
@just-another-jxliu Since this was closed as complete, could you please provide a link to the file?
