### ISSUE TITLE
Alt board not detected by the loader unless the board is reset first

### ISSUE THREAD

**Issue by auxiliary** [Massdrop/mdloader#76]
On MacOS (Mojave), the loader could not detect my connected and functioning Alt keyboard. But if you reset it (put it in programming mode?? if that's correct terminology), it works. I think this should be mentioned in the README as one of the steps if it's actually known by the developers so users are not confused. I finally found this out through some reddit post.

**Comment by vampjaz** [comment]
> Within 60 seconds, press the reset button on your keyboard. For most keyboards running the default firmware, you can hold Fn + b for half a second and release to reset your keyboard

from the readme, last update 5 months ago
