### ISSUE TITLE
Does not work at all on MacOS

### ISSUE THREAD

**Issue by ReagentX** [Massdrop/mdloader#8]
```Christophers-MacBook-Pro:~ chris$ cd Downloads/
Christophers-MacBook-Pro:Downloads chris$ ls
massdrop_alt_md_configurator_1542955916_1242149659.bin
mdloader_mac.dms
Christophers-MacBook-Pro:Downloads chris$ chmod u+x mdloader_mac.dms
Christophers-MacBook-Pro:Downloads chris$ mdloader_mac.dms --first --download massdrop_alt_md_configurator_1542955916_1242149659.bin --restart
-bash: mdloader_mac.dms: command not found

**Comment by Brenntron** [comment]
I had the same issue.
`./mdloader_mac` worked for me

**Comment by egretsRegrets** [comment]
I think this issue may still exist for macOS Catalina users. Prepending the executable with './' does not resolve the issue on my machine. Could be the new OS or it could be that zsh is the new default shell in mac terminals. Or maybe it's just me and it's a PATH issue.

**Comment by egretsRegrets** [comment]
I think the issue I mentioned in the last comment was the result of my somehow missing the mac instruction to 'chmod u+x mdloader_mac to make it executable' on the exec downloads page. Resolved after following this instruction.

**Comment by rgiles008** [comment]
i made the file executable and it still doesnt work when running the `./` command to run the applet-mdflash.bin
